"use client";

import { useState } from "react";

export default function AISection({
  materialId,
  initialSummary,
}: {
  materialId: string;
  initialSummary: string;
}) {
  const [summary, setSummary] = useState(initialSummary);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  async function generateSummary() {
    setLoading(true);
    setError("");
    setSummary("");

    try {
      const response = await fetch("/api/ai/summary", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          materialId,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || "Failed to generate summary");
      }

      setSummary(data.summary);
    } catch (error) {
      setError(error instanceof Error ? error.message : "Something went wrong");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="mt-8 rounded-2xl border border-blue-500/20 bg-blue-500/5 p-6">
      {/* Header */}
      <div className="flex items-center gap-3">
        <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-blue-500/10 text-blue-400">
          ✦
        </div>

        <div>
          <h2 className="font-semibold">AI Study Assistant</h2>

          <p className="text-sm text-slate-400">
            Let Kognii help you understand this material.
          </p>
        </div>
      </div>

      {/* Action */}
      <div className="mt-6">
        <button
          onClick={generateSummary}
          disabled={loading}
          className="rounded-xl bg-blue-500 px-5 py-3 text-sm font-medium transition hover:bg-blue-400 disabled:cursor-not-allowed disabled:opacity-50"
        >
          {loading ? "Generating summary..." : "✦ Generate Summary"}
        </button>
      </div>

      {/* Error */}
      {error && (
        <div className="mt-5 rounded-xl border border-red-500/20 bg-red-500/10 p-4 text-sm text-red-400">
          {error}
        </div>
      )}

      {/* Summary */}
      {summary && (
        <div className="mt-6 rounded-xl border border-slate-800 bg-slate-900 p-6">
          <div className="mb-4 flex items-center justify-between">
            <h3 className="font-semibold">AI Summary</h3>

            <span className="rounded-full bg-blue-500/10 px-3 py-1 text-xs text-blue-400">
              Generated by Gemini
            </span>
          </div>

          <div className="whitespace-pre-wrap text-sm leading-7 text-slate-300">
            {summary}
          </div>
        </div>
      )}
    </div>
  );
}
